Feat/withdrawal testing
ethereum-optimism/optimistic-rollup-integration-tests pull request #39
Opened 2021-01-08 18:40 UTC by alexanderattar

## Description

This PR adds testing for withdrawal from L2 to L1

## Metadata
### Fixes
- Fixes https://github.com/ethereum-optimism/roadmap/issues/226

## Contributing Agreement

- [x] I have read and understood the [Optimism Contributing Guide and Code of Conduct](https://github.com/ethereum-optimism/optimism-monorepo/blob/master/.github/CONTRIBUTING.md) and am following those guidelines in this pull request.

2021-01-08 19:31 UTC, tynes commented on packages/integration-tests/test/actions.spec.ts
> +const l2MessengerJSON = JSON.parse(fs.readFileSync('../../contracts/build/OVM_L2CrossDomainMessenger.json').toString())
You should `require` json files

2021-01-08 19:32 UTC, tynes commented on packages/integration-tests/test/actions.spec.ts
> +const withdraw = async (value) => {
What is your reasoning around having `withdraw` as a function here?

2021-01-08 19:33 UTC, tynes commented on contracts/L1SimpleStorage.sol
> +    uint public totalCount;
Any reason to change this?

2021-01-09 05:05 UTC, K-Ho reviewed
ahh sorry forgot to submit this!

2021-01-09 05:05 UTC, K-Ho commented on packages/integration-tests/test/actions.spec.ts
> +  const L2Messenger = new Contract(process.env.L2_MESSENGER_ADDRESS, l2MessengerJSON.abi, l2Wallet)
As mentioned in slack instead of using `l2MessengerJSON.abi`, use the `messengerInterface` above, so that when we update the contracts your test doesn't break

2021-01-09 05:05 UTC, K-Ho commented on packages/integration-tests/test/actions.spec.ts
> +const l2MessengerJSON = JSON.parse(fs.readFileSync('../../contracts/build/OVM_L2CrossDomainMessenger.json').toString())
Remove

2021-01-09 05:05 UTC, K-Ho commented on packages/integration-tests/test/actions.spec.ts
>  const l1MessengerJSON = getContractInterface('iOVM_BaseCrossDomainMessenger')
rename this to `messengerInterface`

2021-01-09 05:05 UTC, K-Ho commented on packages/integration-tests/test/actions.spec.ts
> +import SimpleStorageJson = require('../../../contracts/build/L1SimpleStorage.json')
This and the file above it are both called `SimpleStorageJson` with different capitalization - would rename them to L1 and L2

2021-01-09 05:05 UTC, K-Ho commented on packages/integration-tests/test/actions.spec.ts
> +import SimpleStorageJson = require('../../../contracts/build/L1SimpleStorage.json')
hmmm also where does this file come from? It seems like you need an L2 -compiled SimpleStorage contract for the deposit test which is specified here: https://github.com/ethereum-optimism/integration-tests/blob/33eddb4f77c9c009b766a64423bbfd4b3c2a3ffe/waffle-config.json#L2. But you also need an L1-compiled Simple storage contract for your withdrawal test, but I don't see where the contract is being compiled with vanilla solc

2021-01-13 18:29 UTC, tynes commented on packages/x-domain/test/actions.spec.ts
> +const withdraw = async (value) => {
What purpose does having the `withdraw` and `deposit` functions serve? It looks like they are just used once

2021-01-13 22:05 UTC, alexanderattar commented
@tynes 
> What purpose does having the withdraw and deposit functions serve? It looks like they are just used once

I can move all the logic into the test itself, but I personally like the separation of the function logic and the test logic for deposit and withdraw. I think it makes it easier to read the test and potentially gives us the opportunity to use withdraw or deposit functions in other tests that might require them. Let me know what you think. Happy to change it if consolidating everything into the tests is preferable for now.

2021-01-15 16:46 UTC, tynes approved these changes

2021-01-15 20:15 UTC, tynes requested changes
Quick change: In the github workflows, this line needs to be updated:
https://github.com/ethereum-optimism/integration-tests/blob/012b024a8cef9c3d7c50b4b6c2d4c2944f78f83c/.github/workflows/tx-ingestion-test.yml#L37
It needs to pass the package name, which was updated to `x-domain`

2021-01-15 22:36 UTC, merged